# Generated by Django 4.2.7 on 2025-08-10 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('notes', 'Notes'), ('calendar', 'Calendar'), ('manual', 'Manual Entry')], max_length=20)),
                ('content', models.TextField(help_text='Raw context content')),
                ('processed_insights', models.JSONField(blank=True, default=dict, help_text='AI-extracted insights')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Extracted keywords')),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment analysis score (-1 to 1)', null=True)),
                ('urgency_indicators', models.JSONField(blank=True, default=list, help_text='Detected urgency keywords/phrases')),
                ('original_timestamp', models.DateTimeField(blank=True, help_text='Original timestamp from source', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('relevance_score', models.FloatField(default=0.0, help_text='AI-calculated relevance for task management')),
                ('related_tasks', models.ManyToManyField(blank=True, help_text='Tasks related to this context', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('deadline', 'Deadline Suggestion'), ('priority', 'Priority Indication'), ('category', 'Category Suggestion'), ('task_creation', 'New Task Suggestion'), ('schedule', 'Schedule Conflict'), ('reminder', 'Reminder Needed')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(help_text='AI confidence in this insight (0-1)')),
                ('suggested_action', models.JSONField(default=dict, help_text='Suggested actions based on insight')),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='context.contextentry')),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyContextSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_entries', models.IntegerField(default=0)),
                ('high_priority_indicators', models.IntegerField(default=0)),
                ('new_task_suggestions', models.IntegerField(default=0)),
                ('deadline_mentions', models.IntegerField(default=0)),
                ('summary_text', models.TextField(blank=True)),
                ('key_themes', models.JSONField(blank=True, default=list)),
                ('priority_areas', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('schedule_suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='contextentry',
            index=models.Index(fields=['user', 'source_type'], name='context_con_user_id_2ecb08_idx'),
        ),
        migrations.AddIndex(
            model_name='contextentry',
            index=models.Index(fields=['created_at'], name='context_con_created_b9d26f_idx'),
        ),
        migrations.AddIndex(
            model_name='contextentry',
            index=models.Index(fields=['relevance_score'], name='context_con_relevan_c6a1ad_idx'),
        ),
    ]
